### ISSUE TITLE
Failed to setup credentials

### ISSUE THREAD

**Issue by pavelpikta** [lean-delivery/ansible-role-jenkins#65]
##### SUMMARY

Unable to resolve next  classes: AWSCredentialsImpl, GitLabApiTokenImpl
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

https://github.com/lean-delivery/ansible-role-jenkins/blob/master/tasks/set_credentials.yml
https://github.com/lean-delivery/ansible-role-jenkins/blob/master/templates/set-credentials.groovy.j2
##### ANSIBLE VERSION

```
2.8.7
```

##### OS / ENVIRONMENT

Linux based
##### STEPS TO REPRODUCE

```yaml
---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-jenkins
      jenkins2_pipeline_libraries_enabled: true
      jenkins2_pipeline_libraries_url: 'https://example.com/example.git'
      jenkins2_bitbucket_project_enabled: true
      jenkins2_sonarqube_enabled: false
      jenkins2_custom_files_enabled: true
      jenkins2_gitlab_enabled: true
      jenkins2_github_enabled: true
      jenkins2_seed_job_enable: true
      gitlab_external_url: 'https://localhost'
      gitlab_project_group: 'test'
      gitlab_project_name: 'test'
      ci_test_jenkins_slave_label: 'ci_slaves'
      feature_verification_jenkins_slave_label: 'fv_slaves'
      ami_for_ci: 'ami-AAAAAAAA'
      ami_for_fv: 'ami-BBBBBBBB'
      ami_for_env: 'ami-CCCCCCCC'
      ami_for_solr: 'ami-9887c6e7'
      lb_security_groups: '"sg-AAAAAAAA","sg-CCCCCCCC"'
      ec2_security_groups: '"sg-BBBBBBBB","sg-DDDDDDDD"'
      aws_key: 'aws_key_name'
      aws_subnet_id: 'subnet-AAAAAAAA'
      artifact_bucket_name: 's3_artifact_test'
      jenkins2_ec2_enable: true
      jenkins2_jira_enabled: true
      jenkins2_globaltools_enable: true
      jenkins2_globaltools_jdk_version:
        - jdk-9.0.4-oth-JPR
      jenkins2_globaltools_maven_version:
        - 3.6.1
      jenkins2_globaltools_ant_version:
        - 1.10.6
      jenkins2_globaltools_nodejs_version:
        - 12.4.0
      jenkins2_globaltools_sonarscanner_version:
        - 3.3.0.1492
      jenkins2_globaltools_sonarscannermsbuild_version:
        - 4.6.2.2108
      jenkins2_globaltools_gradle_version:
        - 5.5-rc-2
      jenkins2_globaltools_docker_version:
        - latest
```

##### EXPECTED RESULTS

Role finished without failed
##### ACTUAL RESULTS

```
     fatal: [test-aws-centos7-jenkins]: FAILED! => changed=false 
1062       msg: |-
1063         script failed with stacktrace:
1064          org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
1065         Script1.groovy: 121: unable to resolve class AWSCredentialsImpl
1066          @ line 121, column 23.
1067            aws_ec2_credentials = new AWSCredentialsImpl(
1068                                  ^
1069       
1070         1 error
1071       
1072                 at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
1073                 at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:958)
1074                 at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:605)
1075                 at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:554)
1076                 at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
1077                 at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
1078                 at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
1079                 at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
1080                 at groovy.lang.GroovyShell.evaluate(GroovyShell.java:584)
1081                 at groovy.lang.GroovyShell.evaluate(GroovyShell.java:623)
1082                 at groovy.lang.GroovyShell.evaluate(GroovyShell.java:594)
1083                 at hudson.util.RemotingDiagnostics$Script.call(RemotingDiagnostics.java:142)
1084                 at hudson.util.RemotingDiagnostics$Script.call(RemotingDiagnostics.java:114)
1085                 at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
1086                 at hudson.util.RemotingDiagnostics.executeGroovy(RemotingDiagnostics.java:111)
1087                 at jenkins.model.Jenkins._doScript(Jenkins.java:4475)
1088                 at jenkins.model.Jenkins.doScriptText(Jenkins.java:4453)
1089                 at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
1090                 at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
1091                 at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)
1092                 at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)
1093                 at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:145)
1094                 at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:535)
1095                 at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
1096                 at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)
1097                 at org.kohsuke.stapler.Stapler.invoke(Stapler.java:878)
1098                 at org.kohsuke.stapler.Stapler.invoke(Stapler.java:676)
1099                 at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
1100                 at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
1101                 at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
1102                 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
1103                 at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
1104                 at io.jenkins.blueocean.ResourceCacheControl.doFilter(ResourceCacheControl.java:134)
1105                 at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
1106                 at io.jenkins.blueocean.auth.jwt.impl.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:61)
1107                 at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
1108                 at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:59)
1109                 at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
1110                 at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:128)
1111                 at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
1112                 at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
1113                 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
1114                 at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:64)
1115                 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
1116                 at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
1117                 at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
1118                 at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
1119                 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
1120                 at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
1121                 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
1122                 at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
1123                 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
1124                 at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
1125                 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
1126                 at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
1127                 at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
1128                 at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
1129                 at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
1130                 at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
1131                 at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
1132                 at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
1133                 at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
1134                 at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
1135                 at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
1136                 at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
1137                 at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
1138                 at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
1139                 at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
1140                 at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
1141                 at org.eclipse.jetty.server.Server.handle(Server.java:505)
1142                 at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
1143                 at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
1144                 at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
1145                 at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
1146                 at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
1147                 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
1148                 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
1149                 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
1150                 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
1151                 at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
1152                 at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
1153                 at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
1154                 at java.lang.Thread.run(Thread.java:748)
1155       output: ''
1156     fatal: [test-aws-Debian9-jenkins]: FAILED! => changed=false 
1157       msg: |-
1158         script failed with stacktrace:
1159          org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
1160         Script1.groovy: 107: unable to resolve class GitLabApiTokenImpl
1161          @ line 107, column 15.
1162            gitlabtoken = new GitLabApiTokenImpl(
1163                          ^
1164       
1165         1 error
1166       
1167                 at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
1168                 at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:958)
1169                 at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:605)
1170                 at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:554)
1171                 at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
1172                 at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
1173                 at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
1174                 at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
1175                 at groovy.lang.GroovyShell.evaluate(GroovyShell.java:584)
1176                 at groovy.lang.GroovyShell.evaluate(GroovyShell.java:623)
1177                 at groovy.lang.GroovyShell.evaluate(GroovyShell.java:594)
1178                 at hudson.util.RemotingDiagnostics$Script.call(RemotingDiagnostics.java:142)
1179                 at hudson.util.RemotingDiagnostics$Script.call(RemotingDiagnostics.java:114)
1180                 at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
1181                 at hudson.util.RemotingDiagnostics.executeGroovy(RemotingDiagnostics.java:111)
1182                 at jenkins.model.Jenkins._doScript(Jenkins.java:4475)
1183                 at jenkins.model.Jenkins.doScriptText(Jenkins.java:4453)
1184                 at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
1185                 at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
1186                 at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)
1187                 at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)
1188                 at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:145)
1189                 at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:535)
1190                 at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
1191                 at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)
1192                 at org.kohsuke.stapler.Stapler.invoke(Stapler.java:878)
1193                 at org.kohsuke.stapler.Stapler.invoke(Stapler.java:676)
1194                 at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
1195                 at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
1196                 at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
1197                 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
1198                 at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
1199                 at jenkins.install.SetupWizard$1.doFilter(SetupWizard.java:628)
1200                 at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
1201                 at io.jenkins.blueocean.ResourceCacheControl.doFilter(ResourceCacheControl.java:134)
1202                 at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
1203                 at io.jenkins.blueocean.auth.jwt.impl.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:61)
1204                 at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
1205                 at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:128)
1206                 at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
1207                 at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
1208                 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
1209                 at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:99)
1210                 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
1211                 at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
1212                 at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
1213                 at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
1214                 at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
1215                 at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
1216                 at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
1217                 at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
1218                 at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
1219                 at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
1220                 at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
1221                 at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
1222                 at jenkins.security.BasicHeaderProcessor.success(BasicHeaderProcessor.java:140)
1223                 at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:82)
1224                 at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
1225                 at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
1226                 at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
1227                 at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
1228                 at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
1229                 at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
1230                 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
1231                 at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
1232                 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
1233                 at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
1234                 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
1235                 at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
1236                 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
1237                 at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
1238                 at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
1239                 at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
1240                 at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
1241                 at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
1242                 at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
1243                 at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
1244                 at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
1245                 at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
1246                 at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
1247                 at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
1248                 at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
1249                 at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
1250                 at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
1251                 at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
1252                 at org.eclipse.jetty.server.Server.handle(Server.java:505)
1253                 at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
1254                 at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
1255                 at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
1256                 at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
1257                 at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
1258                 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
1259                 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
1260                 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
1261                 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
1262                 at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
1263                 at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
1264                 at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
1265                 at java.lang.Thread.run(Thread.java:748)
1266       output: ''
```

**Comment by pavelpikta** [comment]
Not a bug. This was a problem with Jenkins plugin center.
